1. Criação do DataBase e das tables:

CREATE DATABASE "SisCom"
  WITH OWNER = postgres
       ENCODING = 'UTF8'
       TABLESPACE = pg_default
       LC_COLLATE = 'Portuguese_Brazil.1252'
       LC_CTYPE = 'Portuguese_Brazil.1252'
       CONNECTION LIMIT = -1;

CREATE TABLE cliente(
id SERIAL PRIMARY KEY NOT NULL,  
nome VARCHAR(50) NOT NULL,
telefone varchar (50),
endereco varchar (50),
cidade varchar (50),
uf varchar (2),
email varchar (50),
genero varchar (30)
);

create table Usuario (

id SERIAL PRIMARY KEY NOT NULL,
idCliente int not null, 
senha varchar(10));


ALTER TABLE Usuario
ADD CONSTRAINT fk_idCliente FOREIGN KEY (idcliente) REFERENCES cliente (id) MATCH FULL;



create table Produto (
id serial primary key,
descricao varchar(50) not null,
codBar int,
categoria varchar (30),
unidade varchar (30),
custo numeric(12,2),
margemLucro numeric(5,2)
);


create table Venda (

nroCompra SERIAL PRIMARY KEY NOT NULL,
idCliente int not null, 
nomeCliente varchar(50),
totalCompra numeric(12,2),
dataCompra date);

ALTER TABLE Venda
ADD CONSTRAINT fk_idCliente FOREIGN KEY (idcliente) REFERENCES cliente (id) MATCH FULL;

create table ItemVenda (

nroCompra int,
idProduto int, 
nomeProduto varchar(50),
categoria varchar(30),
custo numeric(12,2),
vlrUnitario numeric(12,2),
margemLucro numeric(12,2));


ALTER TABLE ItemVenda
ADD CONSTRAINT fk_nroCompra FOREIGN KEY (nrocompra) REFERENCES venda (nrocompra) MATCH FULL;

ALTER TABLE ItemVenda
ADD CONSTRAINT fk_idProduto FOREIGN KEY (idproduto) REFERENCES produto (id) MATCH FULL;


2. Popular BD:


INSERT INTO cliente (ID,NOME, TELEFONE, ENDERECO, CIDADE, UF, EMAIL, GENERO) VALUES (default,'JOAO','3220-1909','RUA PARANA, 3000','CASCAVEL','PR','JOAO@HOTMAIL.COM','M');
INSERT INTO cliente (ID,NOME, TELEFONE, ENDERECO, CIDADE, UF, EMAIL, GENERO) VALUES (default,'MARIA DA SILVA','3220-1909','RUA PARANA, 3000','CASCAVEL','PR','JOAO@HOTMAIL.COM','M');
INSERT INTO cliente (ID,NOME, TELEFONE, ENDERECO, CIDADE, UF, EMAIL, GENERO) VALUES (default,'PEDRO RAMOS','3219-2389','RUA CARLOS GOMES, 4650','TOLEDO','PR','PEDROR@HOTMAIL.COM','M');
INSERT INTO cliente (ID,NOME, TELEFONE, ENDERECO, CIDADE, UF, EMAIL, GENERO) VALUES (default,'AGATHA CRISTIE','3037-9023','RUA FORTALEZA, 320','BENTO GONCALVES','RS','AGATHA@HOTMAIL.COM','M');
INSERT INTO cliente (ID,NOME, TELEFONE, ENDERECO, CIDADE, UF, EMAIL, GENERO) VALUES (default,'SIDNEY SHELDON','3037-4567','RUA PARANA, 765','ITA','SC','SID@HOTMAIL.COM','M');
INSERT INTO cliente (ID,NOME, TELEFONE, ENDERECO, CIDADE, UF, EMAIL, GENERO) VALUES (default,'JOHN GRISHAM','3220-2357','RUA NEREU RAMOS, 900','UBATUBA','SP','JOHN@HOTMAIL.COM','M');
INSERT INTO cliente (ID,NOME, TELEFONE, ENDERECO, CIDADE, UF, EMAIL, GENERO) VALUES (default,'DAN BROWN','3221-1234','RUA PRES. KENNEDY, 420','VITORIA','ES','DAN@HOTMAIL.COM','M');
INSERT INTO cliente (ID,NOME, TELEFONE, ENDERECO, CIDADE, UF, EMAIL, GENERO) VALUES (default,'LEON TOLSTOI','3219-3456','AV BRASIL, 8790','CASCAVEL','PR','LT@HOTMAIL.COM','M');
INSERT INTO cliente (ID,NOME, TELEFONE, ENDERECO, CIDADE, UF, EMAIL, GENERO) VALUES (default,'LILIAN BROWN','3036-2356','AV GETULIO VARGAS, 2346','GRAMADO','RS','LILIAN@HOTMAIL.COM','M');



INSERT INTO PRODUTO (ID,DESCRICAO, CODBAR, CATEGORIA, UNIDADE, CUSTO, MARGEMLUCRO) VALUES (default,'DOCE DE LEITE',7,'ALIMENTO','KG', 3.45, 15);
INSERT INTO PRODUTO (ID,DESCRICAO, CODBAR, CATEGORIA, UNIDADE, CUSTO, MARGEMLUCRO) VALUES (default,'BALA DE MORANGO',8,'ALIMENTO','PCT500', 1.45, 10);
INSERT INTO PRODUTO (ID,DESCRICAO, CODBAR, CATEGORIA, UNIDADE, CUSTO, MARGEMLUCRO) VALUES (default,'BISCOITO DELICIOSO',5,'ALIMENTO','KG', 9.45, 25);
INSERT INTO PRODUTO (ID,DESCRICAO, CODBAR, CATEGORIA, UNIDADE, CUSTO, MARGEMLUCRO) VALUES (default,'COXINHA',2,'ALIMENTO','UNIDADE', 2.00, 20);
INSERT INTO PRODUTO (ID,DESCRICAO, CODBAR, CATEGORIA, UNIDADE, CUSTO, MARGEMLUCRO) VALUES (default,'LIMPA-VIDROS',12,'LIMPEZA','UNIDADE', 5.00, 20);
INSERT INTO PRODUTO (ID,DESCRICAO, CODBAR, CATEGORIA, UNIDADE, CUSTO, MARGEMLUCRO) VALUES (default,'SHAMPOO',212,'HIGIENE','UNIDADE', 6.00, 25);

